name: 'master_docs'
on:
  workflow_run:
    workflows: ["master_build"]
    branches: [ master ]
    types:
      - completed

env:
  MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

jobs:
  site_job:
    runs-on: ubuntu-latest
    name: Build Microservice Docs
    services:
      rabbitmq:
        image: rabbitmq:3.8
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Install tools
        run: |
          git config --global user.email "ci@example.com"
          git config --global user.name "CI Server"
      - name: Site
        run: >
          ./mvnw site scm-publish:publish-scm
          -DsurefireArgs=-Dspring.profiles.active=ASYNCHRONOUS,TEST
          -Dargs=-Dspring.profiles.active=ASYNCHRONOUS,TEST
          -Dspring.rabbitmq.host=localhost
          -Dscmuser=$PUSHKEY
          -Dscmpublish.pubScmUrl=scm:git:https://$PUSHKEY@github.com/openwms/org.openwms.common.comm.git
          -DdeveloperConnectionUrl=scm:git:https://$PUSHKEY@github.com/openwms/org.openwms.common.comm.git
          -Dci.buildNumber=$GITHUB_RUN_NUMBER
          -B $MAVEN_OPTS
        env:
          PUSHKEY: ${{ secrets.PUSHKEY }}
      - name: Sonar
        run: >
          ./mvnw verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar
          -Dsonar.login=$SONAR_TOKEN
          -Dspring.rabbitmq.host=localhost
          -DsurefireArgs=-Dspring.profiles.active=ASYNCHRONOUS,TEST
          -Dci.buildNumber=$GITHUB_RUN_NUMBER
          -DSONAR_TOKEN=$SONAR_TOKEN
          -Pcoverage -B $MAVEN_OPTS
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
